#golangの最新バージョンのimageを指定
FROM golang:1.16
#作成者情報を記入
# MAINTAINER user <user@example.com>

# 作業用ディレクトリを指定
WORKDIR /go/src/

# カレントディレクトリの全てのファイルやディレクトリをコンテナのrootディレクトリにコピー
COPY . .

RUN go mod init

# APIサーバーで用いたライブラリを取得
RUN go get github.com/davecgh/go-spew 
RUN go get github.com/dgrijalva/jwt-go 
RUN go get github.com/go-sql-driver/mysql 
RUN go get github.com/google/uuid 
# RUN go get github.com/julienschmidt/httprouter 
RUN go get github.com/ussii39/Go_practice
RUN go get golang.org/x/crypto 
RUN go get google.golang.org/appengine 
RUN go get gopkg.in/go-ini/ini.v1 
RUN go get gopkg.in/ini.v1 

# # バイナリーファイルを取得 
# RUN go install github.com/ussii39/Go_practice/web
# # # Linux用バイナリファイルをgo build して取得
# RUN  GOOS=linux GOARCH=amd64 go build ./web/main.go

# ポートの指定
EXPOSE 9000 
#バイナリファイルの実行
CMD [ "./web/main" ]